"""empty message

Revision ID: 65c59eed729a
Revises: 6cfeaf1ef4b6
Create Date: 2025-11-18 19:34:36.209286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c59eed729a'
down_revision: Union[str, Sequence[str], None] = '6cfeaf1ef4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('files', sa.Column('type', sa.String(), nullable=False))
    op.add_column('files', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('files', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('files_user_id_fkey'), 'files', type_='foreignkey')
    op.drop_constraint(op.f('files_post_id_fkey'), 'files', type_='foreignkey')
    op.drop_column('files', 'user_id')
    op.drop_column('files', 'post_id')
    op.add_column('posts', sa.Column('likes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('posts', 'likes')
    op.add_column('files', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('files', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('files_post_id_fkey'), 'files', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('files_user_id_fkey'), 'files', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('files', 'updated_at')
    op.drop_column('files', 'created_at')
    op.drop_column('files', 'type')
    op.drop_table('post_files')
    op.drop_table('avatars')
    # ### end Alembic commands ###
