"""empty message

Revision ID: 92096c8e8edd
Revises: 80d019397f40
Create Date: 2025-12-10 20:35:13.913956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92096c8e8edd'
down_revision: Union[str, Sequence[str], None] = '80d019397f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avatars_user_id'), table_name='avatars')
    op.create_index(op.f('ix_avatars_user_id'), 'avatars', ['user_id'], unique=True)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_avatars_user_id'), table_name='avatars')
    op.create_index(op.f('ix_avatars_user_id'), 'avatars', ['user_id'], unique=False)
    # ### end Alembic commands ###
