"""empty message

Revision ID: f0cf8f61ec4b
Revises: 65c59eed729a
Create Date: 2025-11-24 20:49:05.704567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0cf8f61ec4b'
down_revision: Union[str, Sequence[str], None] = '65c59eed729a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('topic', sa.String(), nullable=True))
    op.create_index(op.f('ix_posts_topic'), 'posts', ['topic'], unique=False)
    op.add_column('users', sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_index(op.f('ix_posts_topic'), table_name='posts')
    op.drop_column('posts', 'topic')
    # ### end Alembic commands ###
